### ISSUE TITLE
Rift Mechanics

### ISSUE THREAD

**Issue by frodare** [ToroCraft/Rifts#2]
## Rift Keystone

Item that is a rare drop from witches and can be found in loot chests.

- right clicking the keystone will attempt to create a rift portal
- if a portal is created (there is enough space) the keystone is consumed
- will have a level encoded in NBT (vanilla loot chests and witches can only drop level 1)
- same level keystones can be crafted together to make a higher level one (l5 + l5 => l6)
- a keystone can be deconstructed into to lower level keystones (l6 => l5 + l5)
- the level of the keystone determines the difficultly level of the rift (GUI free)

## Rift Portal
- the portal will collapse after rift is completed

## Challege
- rift must be completed in 15 minutes in order for the rift guardian to drop to drop the next enough keystones for the player to advance.
- rift guardian will spawn after a set amount of HP has been removed from the rift mobs (future releases could use dropped progress orbs)
- lower level rift keystones will be dropped randomly in the rift (probably current level - (1 or 2))

## Leaderboard

The server will store a leaderboard showing what level players have gotten too and the time it took to defeat the rift guardian.

The leaderboard GUI will be accessible by a Rift Leaderboard item, a craftable item which could possible be hung on walls like paintings.

**Comment by zeriley** [comment]
So, the rift just pops up anywhere?  Interesting.

I actually (surprise surprise) like all this.  Only thing I think I would add is a way to break down a rift keystone to lower level, just in case you combine too far and just get slaughtered.

Also, low chance of keystone in chests, so you don't have to rely purely on random spawns of witches.

**Comment by frodare** [comment]
Awesome! I updated the description.
